/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SISTEMA_DE_INVENTARIO_UNIVERSIDAD_PRIVATE_H
#define SISTEMA_DE_INVENTARIO_UNIVERSIDAD_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.43"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	43
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Sistema de inventario"
#define PRODUCT_VERSION	""

#endif /*SISTEMA_DE_INVENTARIO_UNIVERSIDAD_PRIVATE_H*/
